name: my first workflow
on: 
    push:
        branches:
            main

jobs:
    build:
        runs-on: ubuntu-latest
        steps: 
            - name: reusable-action
              uses: actions/checkout@v3
            - name: text message to you
              run: echo "hii i improve"


        